=== Arkalithe/Portfolio/config.dtd
<!ELEMENT configuration (contactForm)>
<!ELEMENT contactForm (title, helpText, fields, submitButton)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT helpText (#PCDATA)>
<!ELEMENT fields (field+)>
<!ELEMENT field (label, id, type)>
<!ELEMENT label (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT submitButton (#PCDATA)>

=== Arkalithe/Portfolio/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "config.dtd">
<configuration>
    <contactForm>
        <title>Me contacter</title>
        <helpText>Aucune des informations données ne sera partagée.</helpText>
        <fields>
            <field>
                <label>Votre Nom</label>
                <id>nom</id>
                <type>text</type>
            </field>
            <field>
                <label>Votre Prénom</label>
                <id>prenom</id>
                <type>text</type>
            </field>
            <field>
                <label>Votre Adresse Mail</label>
                <id>email</id>
                <type>email</type>
            </field>
            <field>
                <label>Votre Numéro de Téléphone</label>
                <id>telephone</id>
                <type>tel</type>
            </field>
            <field>
                <label>Motif du contact</label>
                <id>description</id>
                <type>textarea</type>
            </field>
        </fields>
        <submitButton>Envoyer</submitButton>
    </contactForm>
    <contactInfo>
        <email>vigneron.tristan.16@gmail.com</email>
        <phone>07-60-51-81-34</phone>
        <cvLink>./assets/pdf/cv.pdf</cvLink>
    </contactInfo>
</configuration>
